### ISSUE TITLE
Unite the reducer flow with the way it currently works

### ISSUE THREAD

**Issue by BlueHotDog** [apollographql/reason-apollo#119]
**Issue Labels**

- [x] feature
- [ ] has-reproduction
- [ ] docs
- [ ] blocking
- [ ] good first issue

Hi all, i'm new to this, but i have a couple of observations - 
The way mutations/queries currently works feels very weird, ReasonReact introduced the concept of a reducer and state and the cycle should be event -> reducer -> update(newState)

but, ReasonApollo works completely differently, its not using the state at all.
Nor does it actually uses the reducer. aside from the fact that i think that the resulting code is very hard to read and reason about since now we have 2 data-flows in each component and we need to think about both.
It also complicates the render function with extra "magic".

I'm not sure how to solve this, but i would love to discuss a solution that actually uses ReasonReact idioms.
For example, why not have 
type state = {
  mutation: Mutation(..., MutationResult)
}

or something like this. in general the fact that i've to write about 5 different "components" to make a simple graph mutation/query feels very very repetitive

**Comment by BlueHotDog** [comment]
i would love to push this forward, i just need some guidance and discussion to make sure i'm headed to the right direction, any maintainer can comment?

**Comment by BlueHotDog** [comment]
I've given it more thought, this is a very rough idea after digging through the code(i wish there were a high level or low level documentation explaining how things work between all the levels - reason-apollo -> react-apollo - apollojs)

what i suggest is maybe another component type apolloReducerComponent(and his friends)
which will make sure that you define another action called ```apolloStateChanged(apolloResponse)```
when you want to run a query/mutation you'll simply call it as normal(not sure whats the pragmatic way of doing this, since its hidden behind 3 levels of abstractions) 
and reasonapollo takes over, and will call your reducer with the action when the apolloResponse changes(from loading to err for example)

This will allow you to pragmatically handle actions and decide on the actual state change resulting from this action(and wether a redraw is needed)

What do you think?

**Comment by kgoggin** [comment]
Hey @BlueHotDog, I'm not an official maintainer (just a an observer and user of this library for a ReasonReact project) but I had a few thoughts/comments.

After reading your suggestions, I think you may be misunderstanding the way React + ReasonReact + Apollo all work together. Both React and ReasonReact have the concept of stateful components, and though they vary in their implementation of this concept (`setState` vs. `reducer`), ultimately they both provide a way for a component to track some internal piece of state that may change over time, and then re-render the view as a result of those changes.

When using Apollo (whether react-apollo or reason-apollo), it maintains its own state in the form of a store. This is external to any component, but components can access the store's data via queries (reads) and mutations (writes). (The fact that the store starts out empty and is populated via network requests to the server is more or less an implementation detail of the API from React's perspective). The react-apollo and reason-apollo APIs both provide the results of a query/mutation via a pattern called [render-props](https://reactjs.org/docs/render-props.html). In this way, Apollo keeps its state external to any one component, while still providing a way for your component to re-render in response to changes because it gets the data it needs from Apollo's state via props. _Apollo is the source of application state, not your component._ That's true in both JS React land, as well as ReasonReact.

There may be instances where you need to do some kind of calculation or manipulation with the result of a query/mutation to get the data in the right form for your component, but 99% of the time that's best handled in the `render` function. For the remaining 1%, you might need to implement a way to dispatch an action that mutates your component state in response to a query/mutation result, similar to the [getDerivedDtateFromProps method](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops) that was recently released in React (be sure to read there about the limited use cases for such a scenario), but I don't think it'd make sense to try to support those use cases in reason-apollo.

Given all that, I don't really see a use case for a specialized component here that aligns to ReasonReact's reducerComponent, as I don't think that's really what you'd want to be doing. If you're using this library to build a UI that connects to a GraphQL server, I'd venture to say that the vast majority of your App's components ought to be stateless, with the exception of those that need to track their own state for something other than the app's data (forms come to mind as the primary example).

I hope that's a helpful explanation and breakdown of the various responsibilities of all the moving parts! When you're trying to mix learning Reason + React + Apollo there's really a ton to keep track of and understand, and Reason especially is very light on real-world examples of much of anything as it's still so new and not as widely used (yet!).

**Comment by BlueHotDog** [comment]
Thank you @kgoggin for the super detailed response - SUPER HELPFUL!
in the case of a query, i agree completely, there's no point of moving a stateless component to a stateful just since you want to do a query.

In case of a mutation, i agree and disagree. i'm not sure what we gain from adding this 2 extra level of indentation(and indirection), i feel that moving the whole thing into the same flow would result in a much cleaner code. i mean, having the mutation send out an action to the component which will result in the reducer being called(and having you explicitly decide if you want to update the code or not) is only a benefit.

i mean, if we compare example code:
```
module AddPokemon = [%graphql {|
  mutation addPokemon($name: String!) {
      addPokemon(name: $name) {
          name
      }
  }
|}];

module AddPokemonMutation = ReasonApollo.CreateMutation(AddPokemon);
let reducer = (action, state) =>
  switch(action) {
    | Apollo(Loading) => /* ...handle loading state... */
  }
let make = (_children) => {
/* ... */,
render: (self) => {  
      <div>
        <button onClick=((_mouseEvent) => {
            AddPokemonMutation.run(
               ~name=state.pokemonName, 
               ~refetchQueries=[|"getAllPokemons"|], 
               self
          })> 
          (ReasonReact.string("Add Pokemon")) 
        </button>
      </div>
}
```
