### ISSUE TITLE
How to use client.query without JSX components?

### ISSUE THREAD

**Issue by zhzhang** [apollographql/reason-apollo#124]
I want to do an initial query on a reducer component's didMount function, which should just update the component's state with the result and not render anything. This would be closest to this behavior in ApolloClient
```
client
  .query({
    query: gql`
      {
        rates(currency: "USD") {
          currency
        }
      }
    `
  })
  .then(result => console.log(result));
```
found here https://www.apollographql.com/docs/react/essentials/get-started.html
I don't see an example of how to do this in the docs. Is there a reason that all of the examples in the docs are JSX components, and there are no imperative usages of Client's query function? (i.e. is that an antipattern?)

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [x] docs
- [ ] blocking
- [ ] good first issue

**Comment by thangngoc89** [comment]
You can get the client from here https://github.com/apollographql/reason-apollo#apolloconsumer 

This repository is a directly binding to react-apollo, not apollo-client

**Comment by zhzhang** [comment]
Sure, I can use ApolloConsumer, but this requires that I return some dummy JSX at some point, when all that I am looking to do is send a request and process the response in a callback.
There are bindings for the apollo-client query and mutation methods in ReasonApollo, see https://github.com/apollographql/reason-apollo/blob/ac50f89a895e06fd472ec5d9c79482e92a24a358/src/ApolloClient.re#L17
Is there a reason why they're not exposed directly, rather than through the ApolloConsumer component? Admittedly, I'm not sure that what I'm aiming to do is idiomatic to ReasonApollo, and if that's the case I'm curious to hear the reason why so that I can structure my code better.

**Comment by Gregoirevda** [comment]
apolloClient API provides a `query` method, which is just an http call with the query you provide, and a `watchQuery` method. You could just use the `query`, but then if you mutate your GraphQL API, you'll have to handle the fetching of the result again as well as merging, optimisations,...
`watchQuery` is a bit better: it is making an http request + listening to local apollo state changes based on the query you pass. So you'll always render the latest data, often even without making an http request.

Handling all this is complex and that's what react-apollo provides (it only uses `watchQuery`). Reason-apollo are bindings around react-apollo.

Can't you return JSX that displays the data?

**Comment by zhzhang** [comment]
@Gregoirevda I need to update the state of a reducer component with the query results. I'm trying to page through comments with offset based pagination and have a reducer component whose state stores the loaded comments. This doesn't work if I have to catch the result in a ReasonApollo JSX component, because if I try to send an action to the reducer in the middle of an update it throws, saying that I can't call send while the component state is being updated.

However, thinking about the use case some more, it seems like Apollo can support this already https://www.apollographql.com/docs/react/features/pagination.html and I don't really need to store the list of comments in the state if Apollo is already updating it.

Will close this issue for now and reopen if I run into an actual use case that requires a raw query.

**Comment by Gregoirevda** [comment]
Please share if your pagination worked

**Comment by zhzhang** [comment]
@Gregoirevda I ran into a tricky issue:
I have a comments component wrapped in a `<GetCommentsQuery>` and a document component wrapped in `<GetDocumentDataQuery>`. These two components need to talk to each other: specifically highlights in the document need to be referenced within comments.
Sharing stated between these two components is tricky because Apollo seems to only push state downwards into child components, but the shared state would ideally sit in a Reducer component that wraps the comment and document ones.
I'm not sure that placing both query components at a higher level makes sense, as that would imply that whenever there are components with multiple queries and shared state, there would need to be a bunch of nested query components with all of the application components inside.
Any thoughts?

**Comment by dkao1978** [comment]
I am a bit surprised that this isn't more of an issue. How are people making graphql queries through JSX and updating the local state? I would love to understand a pattern that works through JSX.

Here is how we've pieced together a query in didMount:

```
Module ReactlessApolloClient = {
open ApolloInMemoryCache;

type dataObject = {
  .
  "__typename": string,
  "id": string,
};

/* Create an InMemoryCache */
let inMemoryCache =
  createInMemoryCache(~dataIdFromObject=(obj: dataObject) => obj##id, ());

/* Create an HTTP Link */
let httpLink =
  ApolloLinks.createHttpLink(~uri="http://localhost:8000/graphql", ());

let client =
  ReasonApollo.createApolloClient(~link=httpLink, ~cache=inMemoryCache, ());

[@bs.module] external gql: ReasonApolloTypes.gql = "graphql-tag";

}
```
```
type allOrdersApollo = {. "data": data}
and data = {. "_allOrdersMeta": meta}
and meta = {. "count": int};

external toApolloResult: string => Js.Promise.t(allOrdersApollo) =
  "%identity";

module Orders = {
  /* component setup */
  didMount: self => {
    let gql = ReactlessApolloClient.gql;
    let apolloClient = ReactlessApolloClient.client;

    let allOrdersMeta = GetOrdersMeta.make();
    let query: ApolloClient.queryObj = {
      "query": gql(. allOrdersMeta##query),
      "variables": allOrdersMeta##variables,
    };
    let apolloData = apolloClient##query(query);
    let apolloData = toApolloResult(apolloData);
    let results =
      apolloData
      |> Js.Promise.then_(value => {
           let count = value##data##_allOrdersMeta##count;
           self.send(UpdateCount(count));
           Js.Promise.resolve(count);
         });
    ();
  },

```

**Comment by kgoggin** [comment]
@zhzhang I'm curious about exactly what's being "shared" between your two components? Is it the result of a query from the server, or some bit of state that's inherently local to the client only? If it's a query result, I'd say you just need to make your two components query the same data. Apollo is smart enough to only get the data from the server once, and then pass the same data to both components. If it's client-only state, then this isn't really a GraphQL problem, right? 

> Apollo seems to only push state downwards into child components

I think this is a bit of a misconception. It's true that, when using the component-based API a component that's dependent on query data must be a child of a Query component. But the "state" exists outside the component tree altogether in Apollo's cache and is provided via the context wherever its needed. Having learned Redux prior to Apollo/GraphQL, I find it helpful to think of Apollo's cache as the "store", and the queries are essentially the "selectors" you'd write to get some data out of the store. The fact that the data is actually coming from the server if it's not in the store already is essentially an implementation detail. 

@dkao1978 I think this also answers your question about why this isn't "more of an issue". Using the results of a query to update a component's local state is generally an anti-pattern. In your example, why not just access `count` directly from the query result in the `render` method? What you're doing there is "derived state" (state that's based on something coming in from somewhere else) and it's [generally not a great idea](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html).

**Comment by dkao1978** [comment]
@kgoggin I'm a bit of a Reason/ReasonReact beginner so I'm not sure how I would use a local variable inside of didMount in the render function without going through the reducer.

I agree that "derived state" is subpar. I spent quite a bit of time trying to use Apollo's cache in Reason and I gave up. It was such a pain and the resulting code was atrocious. Having to write:
```
<ApolloConsumer>
...((apolloClient) => {
        let count = apolloClient##store##data##count;       
        }
</ApolloConsumer>
```
everywhere in the code is really ugly compared to 

```
self.state.count
```

If someone has a better pattern, please share!

**Comment by kgoggin** [comment]
@dkao1978 you're right, using a reducer component is definitely the right way to handle setting a value in `didMount` that affects what you're rendering - you're not missing anything there. But, what I'm saying is that you should be able to avoid using local state entirely. Your component is directly dependent on the result of the query, and sticking that result in the component's state is just adding an extra layer to your state management.

Why are you trying to use the client/cache directly in the component instead of using the `<Query>` API? Accessing the cache directly is almost certainly not what you want to do - you're bypassing Apollo's ability to fetch the data if it's not already in the cache. Your code won't look _too_ much different than what you put above if you're using `<Query>` instead of `<ApolloConsumer>`, so if you've got a big problem with the aesthetics that's probably not going to help much, but that's the idiomatic way to use Apollo, whether it's in plain JS or ReasonML (though I will concede needing to access the query fields with `##` instead of just a `.` is kind of annoying).

I'm not sure if this is what you're saying exactly, but when I first started writing Reason code with GraphQL I felt like I was writing a lot more code to do the same things that I was used to doing in JS. Eventually I realized that the language features of Reason were actually pushing me to actually cover more real scenarios that were easy to ignore in JS. Nullable fields, loading and error states - all things you can get away with ignoring in JS code but which Reason will "make" you worry about these things - resulting in better code overall!

Anyway, hope that's helpful. Welcome to Reason-land! Once you start to get the hang of it it really is pretty great!

**Comment by zhzhang** [comment]
@kgoggin I am trying to share a list of comments between two components that can both write data to any particular comment. The reason I want this piece of state to be explicitly stored in a reducer component rather than inside the Apollo cache is because I want to be able to edit comments or add new comments, and have the changes only be sent via graphql on an explicitly save operation.

**Comment by kgoggin** [comment]
@zhzhang so in that scenario I'd still try to avoid duplicating all of the comment data in the local component state by only tracking the mutations that are pending. For edits, track the comment id + new data (I'd probably use the `Js.Dict` type for that because it'd be easy to look up any changes by id), and then track a list of new comments. Then in your render function, you combine the comments list from the query with your list of pending mutations from local state to create the "final" list of comments to show in the UI.

Also that scenario sounds different than what you were [describing earlier](https://github.com/apollographql/reason-apollo/issues/124#issuecomment-412795076) - does this still have to do with being able to use the Apollo client directly outside of any JSX?

(I don't at all mean to suggest I know exactly how to solve your problem, of course - just suggesting that there's _usually_ a way to avoid duplicating state in two places, which _usually_ simplifies things a good bit.)

**Comment by zhzhang** [comment]
Yea, my initial intent for using Apollo client outside of JSX was to be able to use the results to update state without hitting the "cannot setState during an update" error.

You're right that only tracking the new mutations in component state would work, but it makes the code a bit messier as now there are two sources of truth (Apollo + local state) that have to be merged to render the comments component.

I think the ideal design in this case actually would be to maybe expose handlers in Apollo that can, for example, merge graphql data into explicitly managed redux state or something similar. It's really the fact that the the Apollo cache is abstracted away that makes some of these use cases a little less clean than they could be (to my admittedly small amount of Apollo knowledge at least).

**Comment by zhzhang** [comment]
@kgoggin After working on this a bit more, it turns out that the cleanest, most natural solution regardless of framework was to keep the pending mutations separate. That was a good insight. I originally thought that having as few components/functions responsible for each type of data (in this case comments) was the right way to go, but it turns out that for use cases like comments, the treatment of new comments vs ones that had already been written to the back end are different enough that handling them separately makes more sense.
