### ISSUE TITLE
Version compatibility issue with ReasonApolloMutation.re ?

### ISSUE THREAD

**Issue by JulioBarros** [apollographql/reason-apollo#226]
I'm new to reason and reason-apollo so I hope this is not an obvious issue and thanks in advance.

I've followed the read me instructions to the best of my ability but am getting an error: "The module or file ApolloInMemoryCache can't be found."

I generated the project with bsb -init so there is a script and did an npm start.

I've checked my bsconfig.json
"bs-dependencies": ["reason-react", "reason-apollo"],
  "ppx-flags": ["@baransu/graphql_ppx_re/ppx6"],

and package.json

"dependencies": {
    "apollo-utilities": "^1.3.3",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "reason-apollo": "^0.18.0",
    "reason-react": ">=0.7.0"
  },
  "devDependencies": {
    "@baransu/graphql_ppx_re": "^0.6.1",
    "bs-platform": "^7.1.0",
    "moduleserve": "^0.9.0"
  }

I think the whole package is not compiling and when I do an 'npm run build' I get the following error:

We've found a bug for you!
  /Users/julio/projects/BuildStrongConnections/reason-client/node_modules/reason-apollo/src/graphql-types/ReasonApolloMutation.re 133:10-29

  131 ┆ let make =
  132 ┆     (
  133 ┆       ~variables: Js.Json.t=?,
  134 ┆       ~onError: apolloError => unit=?,
  135 ┆       ~onCompleted: unit => unit=?,

  ReasonReact: optional argument annotations must have explicit option. Did you mean option(Js.Json.t)=??

It feels like a version incompatibility / regression. Any tips or ideas appreciated. Thanks in advance.

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [x] blocking
- [ ] good first issue

**Comment by yawaramin** [comment]
The issue was discussed in Discord and, as I understand it, this compile error is happening because of a ReasonReact JSX bugfix that was shipped in bs-platform 7.1.0. This was fixing an unsoundness issue (cf. @rickyvetter) and was considered important to get out the door.

The compile error pasted above comes from this piece of code: https://github.com/apollographql/reason-apollo/blob/f06928905879cf6b19eee0ef08de6653ab8221e8/src/graphql-types/ReasonApolloMutation.re#L129

Personally, my recommendation would be to get rid of type annotations from values and functions in implementation files. I consider this to be more idiomatic anyway. Plus it should work across both BuckleScript 7.1.0 and earlier. It would look like this:

```reason
// src/graphql-types/ReasonApolloMutation.re

[@react.component]
  let make =
      (
        ~variables=?,
        ~onError=?,
        ~onCompleted=?,
        ~children,
      ) => ...
```

I realize people will need type annotations–they can be put in the corresponding interface files, e.g.

```reason
// src/graphql-types/ReasonApolloMutation.rei

[@react.component]
let make =
      (
        ~variables: Js.Json.t=?, // No option needed! :-)
        ~onError: apolloError => unit=?,
        ~onCompleted: unit => unit=?,
        ~children: (apolloMutation, renderPropObj) => React.element,
      ) =>
    React.element;
```

And so on.

cc @sgrove @idkjs

**Comment by idkjs** [comment]
Where are we fixing this? Is on https://github.com/idkjs/reason-apollo/tree/bs_platform_7? Or master?

**Comment by rickyvetter** [comment]
Yeah agree that removing annotations in implementation is probably the easiest and most idiomatic way to do this.

**Comment by idkjs** [comment]
Where are we fixing this? Is on https://github.com/idkjs/reason-apollo/tree/bs_platform_7? Or master?

**Comment by yawaramin** [comment]
@idkjs in this repo itself. See my comment above (code examples have file names).

**Comment by idkjs** [comment]
I guess master since its on bs-platform 7 already.

**Comment by yawaramin** [comment]
Oh sorry you were asking about the branch. I would say master.
