### ISSUE TITLE
Make graphql_ppx optional?

### ISSUE THREAD

**Issue by bkonkle** [apollographql/reason-apollo#31]
I don't want to make my devs get `opam` up and running on their machines to install `graphql_ppx` - I'd like to rely entirely on `yarn`. Is there any way to make the `graphql_ppx` dependency optional?

**Comment by bkonkle** [comment]
I'm actually having trouble getting it working, myself. Even after installing opam and running `opam install graphql_ppx`, I'm getting this when I build:

```
Could not resolve  graphql_ppx/ppx in /Users/brandon/code/mj4co-client
Fatal error: exception Failure("graphql_ppx/ppx not found when resolving ppx-flags")
error Command failed with exit code 2.
```

**Comment by bkonkle** [comment]
It turns out this is because I hadn't restarted my shell after initializing opam, so it wasn't picking up installed packages.

Regardless, I think it illustrates my point. 😅  It's non-trivial to set this up, and if I'm not using `graphql_ppx` to write my queries I get no benefit for all of the effort.

**Comment by kgoggin** [comment]
@bkonkle did you also install the npm dependency? I'm fairly sure the `graphql_ppx/ppx` reference in `bsconfig.json` is a reference to the npm dependency, which itself depends on the opam package being installed.

I had an issue because I installed the npm dep first and then got the opam one working, but there's a postinstall script that runs in the npm that depends on the opam dep, so I had to reinstall it to get that to all work correctly.

Suffice it to say: there's definitely room for improving the developer experience for all of this.

**Comment by Gregoirevda** [comment]
@bkonkle We are working on that with the `graphql_ppx` maintainers. Since all opam libraries can be deployed on npm with esy, that's what we're doing. So I'd say in 2 weeks you'll just have a `yarn add graphql-ppx` and that will work.
You could skip `graphql_ppx`, but you'll have to write by yourself the `parse`, `query` and `variables` properties on an new object... And you wont have type safety. 
Would you still want to skip graphql_ppx if it's all installable with a yarn command?

**Comment by jthegedus** [comment]
Just a lurkers 2c.

As a newcomer to the Reason scene, I've been finding it difficult to know which tools to use for what, and what output I should be targeting. With the `bs-platform`, `esy`, JS interop through Bucklescript and compiling to JS vs Native it's a chore just to pick. I understand that the whole opam community *probably* feels very "get off my lawn!"-ish to the npm ecosystem. It would be awesome if all new packages written in Reason could be used by both communities, but if I had to pick one to support here, it seems like the npm ecosystem is the way to go since this package is an npm package itself. Or is it also on Opam?

Sorry for the interruption.

**Comment by Gregoirevda** [comment]
Currently, one part is on npm (`send-introspection-query` and binding with the ppx) and the other one is on opam (ppx). But were're working on setting all of them in npm. It's being tested right now

**Comment by bkonkle** [comment]
@Gregoirevda That's excellent news! Let me know if you need a guinea pig to test things out on. I'm using this actively for something that should be in production in a couple weeks, so some of this is on me for being a crazy early adopter. 😁  This means I'll be deep in the code for a while, though, and should be able to help. 👍

**Comment by kgoggin** [comment]
@Gregoirevda I'd also be happy to help test this out! We're trying to get our CI set up and running into some complexities with the current install process so if there's a chance this would help simplify things I'd love to give it a shot. Thanks!

**Comment by codekiln** [comment]
I am also having some trouble getting this to work. My opam is set to `4.02.3`. I completed these:

```
$ yarn add reason-apollo
$ opam install graphql_ppx
$ yarn add --dev graphql_ppx
```

Each of these succeeds.

```
$ bsb -make-world
[14/14] Building src/ReasonReactOptimizedCreateClass.mlast.d
[7/7] Building src/ReactDOMRe.cmj
[1/14] Building src/ReasonApolloTypes.mlast
FAILED: src/ReasonApolloTypes.mlast 
/Users/pnore/.nvm/versions/node/v9.5.0/lib/node_modules/bs-platform/lib/bsc.exe -pp "/Users/pnore/.nvm/versions/node/v9.5.0/lib/node_modules/bs-platform/lib/refmt3.exe --print binary" -ppx '/Users/pnore/.nvm/versions/node/v9.5.0/lib/node_modules/bs-platform/lib/reactjs_jsx_ppx_2.exe'  -ppx /Users/pnore/dev/django-react-chat/django_react_chat_example_project/node_modules/graphql_ppx/ppx -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I '/Users/pnore/dev/django-react-chat/django_react_chat_example_project/node_modules/bs-platform/lib/ocaml' -bs-super-errors -no-alias-deps -color always -c -o src/ReasonApolloTypes.mlast -bs-syntax-only -bs-binary-ast -impl /Users/pnore/dev/django-react-chat/django_react_chat_example_project/node_modules/reason-apollo/src/ReasonApolloTypes.re
Graphql_ppx.Schema_file_not_found

  We've found a bug for you!
  /Users/pnore/dev/django-react-chat/django_react_chat_example_project/node_modules/reason-apollo/src/ReasonApolloTypes.re
  
  There's been an error running a preprocessor before the compilation of a file.
  This was the command:
  
  /Users/pnore/dev/django-react-chat/django_react_chat_example_project/node_modules/graphql_ppx/ppx '/var/folders/vd/_cgkbpk16sx746c9_0cf3r51dn9jy9/T/camlppx04ff99' '/var/folders/vd/_cgkbpk16sx746c9_0cf3r51dn9jy9/T/camlppx8434fd'

```

There are about 14 errors like that. Any tips on debugging?

**Comment by Gregoirevda** [comment]
@codekiln You need to run `yarn send-introspection-query http://my-api.example.com/api` with your graphql endpoint.
This will create a `graphql-schema.json` file. Which the ppx needs to read into

**Comment by codekiln** [comment]
@Gregoirevda thanks for the tip. I already had `graphql.schema.json`, but it looks like `graphql_ppx` was expecting it to be called `graphql_schema.json`. The `README` currently says the file should be called `schema.json`, would that have worked too?.

**Comment by Gregoirevda** [comment]
@codekiln No, I'll update the README. Thanks for pointing out! 
graphql_ppx only supports `graphql_schema.json`: https://github.com/mhallin/graphql_ppx/blob/689ed6bb73304388bff761594e55f51090c90f3c/src/graphql_ppx.ml#L46

**Comment by excitement-engineer** [comment]
graphql_ppx is now on npm, now need for opam! See #40

**Comment by Gregoirevda** [comment]
Yes, I'll update that. Note that it needs node v8+ currently

**Comment by Gregoirevda** [comment]
You don't have to use opam anymore: https://github.com/apollographql/reason-apollo/pull/40/files
